import fs from 'node:fs';
import path from 'node:path';
import { SbxError } from '../domain/SbxError.mjs';

const MANIFEST_FILENAME = 'sandbox.config.mjs';

/**
 * Writes a starting manifest into a project that has none.
 *
 * What it fills in is what can be read off the repository without guessing:
 * the project name and the install command for the toolchain it found.
 * Ports, services and seeds are left as commented scaffolding — those are
 * decisions, and a plausible wrong value is worse than an empty one because
 * it looks reviewed.
 */
export class ManifestScaffolder {
  constructor(catalog) {
    this.catalog = catalog;
  }

  /** @throws when a manifest already exists. @returns what was detected and where it was written. */
  scaffold(projectDirectory) {
    const manifestPath = path.join(projectDirectory, MANIFEST_FILENAME);
    if (fs.existsSync(manifestPath)) {
      throw new SbxError(`${manifestPath} already exists.`, 'Edit it, or delete it to start over.');
    }
    const detected = this.detect(projectDirectory);
    const projectName = path.basename(path.resolve(projectDirectory));
    fs.writeFileSync(manifestPath, this.render(projectName, detected));
    return { manifestPath, projectName, ...detected };
  }

  detect(projectDirectory) {
    for (const entry of this.catalog.entries()) {
      if (fs.existsSync(path.join(projectDirectory, entry.marker))) return entry;
    }
    return { marker: null, ecosystem: 'unrecognized', install: null };
  }

  render(projectName, detected) {
    return `/**
 * How \`sbx\` builds a sandbox of this repo. Generated by \`sbx init\`;
 * the commented blocks are the decisions it would not guess for you.
 *
 * Run \`sbx doctor\` after editing — it reports what would break before
 * you spend a create on finding out.
 */
export default {
  name: '${projectName}',

  ports: {
    // REPLACE THESE. One entry per port your stack binds, with the value
    // it uses today. Slot 0 is this checkout on exactly these numbers;
    // sandbox N shifts every one of them by N x stride.
    //
    // Your app has to read them from the environment. A hardcoded port in
    // a config file is what makes two sandboxes collide.
    base: { app: 3000 },

    // Optional. A role with no entry here is published as ROLE_PORT,
    // so \`app\` above arrives as APP_PORT. Name a variable only when your
    // project already expects a different one.
    // env: { app: 'SERVER_PORT' },

    stride: 10,
    maxSlots: 9,
  },

  // Stateful services, one Compose project per sandbox. Ports inside it
  // come from the block above: "\${APP_PORT}:3000". Delete this line if
  // your project keeps its state in files inside the worktree.
  // compose: 'sandbox/compose.yml',

  // Files rendered into each sandbox from a template in the repo.
  // Placeholders are \${...} and resolve against the port block, the
  // generated secrets, and ~/.sbx/${projectName}/secrets.env.
  // env: [{ from: 'sandbox/templates/app.env', to: '.env' }],

  // Minted once per sandbox and stored with it, never rotated.
  // generate: { SESSION_SECRET: 32 },

  // Shell commands run from the worktree root with the sandbox's
  // variables in the environment. \`create\` runs install, migrate and
  // seed in that order; \`sbx seed --reset\` runs reset then seed.
  hooks: {
${this.renderHooks(detected)}
  },
};
`;
  }

  renderHooks(detected) {
    const install = detected.install
      ? `    install: '${detected.install}',`
      : '    // install: ...   (no toolchain recognized in this directory)';
    return [
      install,
      '    // migrate: ...',
      '    // seed: ...',
      '    // reset: ...',
    ].join('\n');
  }
}
